### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by IgnorantGeek** [pmaris/pynextbus#3]
When trying to import the py_nextbus module, I get the following error. I haven't been able to figure out what it means.

`Traceback (most recent call last):
  File "/home/nick/Documents/Workspaces/BusScheduler/HomeBusSchedule.py", line 1, in <module>
    import py_nextbus
  File "/home/nick/Documents/Workspaces/BusScheduler/py_nextbus/__init__.py", line 3, in <module>
    from .client import NextBusClient
  File "/home/nick/Documents/Workspaces/BusScheduler/py_nextbus/client.py", line 3, in <module>
    from urllib.error import HTTPError
ImportError: No module named error`

**Comment by IgnorantGeek** [comment]
The issue is with the import statements in client.py.

**Comment by ViViDboarder** [comment]
I suspect you're using some Python 2 version. This only supports 3+.
